ServiceConfig:
  model_path: /tmp/n3u-fp4
  served_model_path: /tmp/n3u-fp4
  include_frontend: true
  prefix: 92000
  hf_token: null
  served_model_name: /tmp/n3u-fp4
  model_name: /tmp/n3u-fp4
  head_node_ip: 0.0.0.0
  port: 8000
  sglang_kv_event_port: 5557
K8sConfig:
  name_prefix: dynamo
  k8s_namespace: null
  k8s_image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:1.2.0
  k8s_planner_image: null
  k8s_image_pull_secret: null
  transport: null
  k8s_pvc_name: ''
  k8s_model_path_in_pvc: ''
  k8s_pvc_mount_path: /workspace/model_cache
  k8s_model_cache: ''
  k8s_etcd_endpoints: null
  k8s_hf_home: ''
  name: dynamo-agg
  k8s_engine_mode: null
  use_engine_cm: false
  prefill_engine_args: /workspace/engine_configs/prefill_config.yaml
  decode_engine_args: /workspace/engine_configs/decode_config.yaml
  agg_engine_args: /workspace/engine_configs/agg_config.yaml
DynConfig:
  mode: agg
  enable_router: false
WorkerConfig:
  prefill_workers: 0
  decode_workers: 0
  agg_workers: 6
  prefill_gpus_per_worker: null
  decode_gpus_per_worker: null
  agg_gpus_per_worker: 4
SlaConfig:
  isl: 96000
  osl: 900
  ttft: 408.513
  tpot: 9.924
BenchConfig:
  name: dynamo-agg-benchmark
  image: python:3.12-slim
  profile_start_timeout: 400
  endpoint_type: chat
  endpoint_url: http://dynamo-agg-frontend.None.svc.cluster.local:8000
  model: /tmp/n3u-fp4
  tokenizer: /tmp/n3u-fp4
  isl: 96000
  osl: 900
  isl_stddev: 0
  osl_stddev: 0
  prefix_prompt_pool_size: 1
  concurrency:
  - 1
  - 2
  - 4
  - 8
  - 32
  - 64
  - 128
  - 256
  num_requests:
  - 50
  - 100
  - 200
  - 400
  - 1600
  - 3200
  - 6400
  - 12800
  ui: simple
  image_batch_size: 0
SflowConfig:
  slurm_account: null
  slurm_partition: null
  slurm_timelimit: 120
  aiperf_image: python:3.12-slim
  extra_frontend_args: null
  dynamo_image: null
  variable_profile: null
NodeConfig:
  num_gpus_per_node: 4
  system_name: gb300
params:
  prefill: {}
  decode: {}
  agg:
    tensor_parallel_size: 4
    pipeline_parallel_size: 1
    data_parallel_size: 1
    gpus_per_worker: 4
    moe_tensor_parallel_size: 2
    moe_expert_parallel_size: 2
    max_batch_size: 8
    gemm_quant_mode: fp8_static
    moe_quant_mode: nvfp4
    kvcache_quant_mode: fp8
    fmha_quant_mode: fp8
    comm_quant_mode: half
    memory: 124.178
    kv_cache_dtype: fp8
ModelConfig:
  prefix: 92000
  is_moe: true
  nextn: 0
