apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: dynamo-disagg
spec:
  services:
    Frontend:
      envFromSecret: hf-token-secret
      componentType: frontend
      replicas: 1
      extraPodSpec:
        nodeSelector:
          kubernetes.io/arch: arm64
          nvidia.com/gpu.product: NVIDIA-GB200
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:1.2.0
          imagePullPolicy: IfNotPresent
          command:
          - python3
          - -m
          - dynamo.frontend
          args:
          - --http-port
          - '8000'
      envs:
      - name: DYN_ROUTER_MODE
        value: kv
    SGLangPrefillWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: prefill
      replicas: 1
      resources:
        limits:
          gpu: '4'
      sharedMemory:
        size: 64Gi
      extraPodSpec:
        nodeSelector:
          kubernetes.io/arch: arm64
          nvidia.com/gpu.product: NVIDIA-GB200
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:1.2.0
          workingDir: /workspace/components/backends/sglang
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          args:
          - "set -euo pipefail\nargs=(\n  --model-path \"/tmp/n3u-fp4\"\n  --served-model-name\
            \ \"/tmp/n3u-fp4\"\n  --tensor-parallel-size 4 --pipeline-parallel-size\
            \ 1 --data-parallel-size 1 --kv-cache-dtype fp8_e4m3 --max-running-requests\
            \ 1 --max-prefill-tokens 97500 --expert-parallel-size 4 --disaggregation-transfer-backend\
            \ nixl --moe-runner-backend deepep_moe\n)\nargs+=(--host \"0.0.0.0\")\n\
            args+=(--disaggregation-mode prefill)\nargs+=(--kv-events-config '{\"\
            publisher\":\"zmq\",\"topic\":\"kv-events\",\"endpoint\":\"tcp://*:5557\"\
            }')\nexec python3 -m dynamo.sglang \"${args[@]}\"\n"
          env:
          - name: NCCL_CUMEM_ENABLE
            value: '1'
          - name: NCCL_MNNVL_ENABLE
            value: '1'
          - name: NCCL_NVLS_ENABLE
            value: '1'
          - name: NCCL_P2P_LEVEL
            value: NVL
          - name: UCX_CUDA_IPC_ENABLE_MNNVL
            value: "y"
          - name: VLLM_USE_NCCL_SYMM_MEM
            value: '1'
    SGLangDecodeWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: decode
      replicas: 5
      resources:
        limits:
          gpu: '4'
      sharedMemory:
        size: 128Gi
      extraPodSpec:
        nodeSelector:
          kubernetes.io/arch: arm64
          nvidia.com/gpu.product: NVIDIA-GB200
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:1.2.0
          workingDir: /workspace/components/backends/sglang
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          args:
          - "set -euo pipefail\nargs=(\n  --model-path \"/tmp/n3u-fp4\"\n  --served-model-name\
            \ \"/tmp/n3u-fp4\"\n  --tensor-parallel-size 4 --pipeline-parallel-size\
            \ 1 --data-parallel-size 1 --kv-cache-dtype fp8_e4m3 --max-running-requests\
            \ 512 --max-prefill-tokens 97500 --expert-parallel-size 2 --disaggregation-transfer-backend\
            \ nixl --cuda-graph-bs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 16 20 24\
            \ 28 32 32 40 48 56 64 64 80 96 112 128 128 160 192 224 256 256 320 384\
            \ 448 512 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 --moe-runner-backend deepep_moe\n\
            )\nargs+=(--host \"0.0.0.0\")\nargs+=(--disaggregation-mode decode)\n\
            args+=(--kv-events-config '{\"publisher\":\"zmq\",\"topic\":\"kv-events\"\
            ,\"endpoint\":\"tcp://*:5557\"}')\nexec python3 -m dynamo.sglang \"${args[@]}\"\
            \n"
          env:
          - name: NCCL_CUMEM_ENABLE
            value: '1'
          - name: NCCL_MNNVL_ENABLE
            value: '1'
          - name: NCCL_NVLS_ENABLE
            value: '1'
          - name: NCCL_P2P_LEVEL
            value: NVL
          - name: UCX_CUDA_IPC_ENABLE_MNNVL
            value: "y"
          - name: VLLM_USE_NCCL_SYMM_MEM
            value: '1'
